version: "3.8"
services:
  redis:
    image: "redis:7-alpine"
    command: redis-server --appendonly yes
    volumes:
      - "redis:/data"

  sidekiq:
    depends_on:
      - "redis"
    build: .
    env_file: .env
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production
      RUBY_YJIT_ENABLE: 1
    volumes:
      - ./:/app

volumes:
  redis:

