version: "3.8"
services:
  redis:
    image: "redis:7-alpine"
    command: redis-server
    volumes:
      - "redis:/data"

  sidekiq:
    depends_on:
      - "redis"
    image: "ghcr.io/minter/rod_the_bot:latest"
    env_file: .env
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production
    volumes:
      - ./:/app

volumes:
  redis:

