version: "3.8"
services:
  redis:
    image: "redis:7-alpine"
    command: redis-server
    volumes:
      - "redis:/data"

  sidekiq:
    depends_on:
      - "redis"
    build: .
    env_file: .env
    command: bundle exec sidekiq
    extra_hosts:
      - "statsapi.web.nhl.com:18.66.2.22"
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production
    volumes:
      - ./:/app

volumes:
  redis:

